//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySad
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public Nullable<double> Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronomyc { get; set; }
        public string Emai { get; set; }
        public Nullable<System.DateTime> BirthName { get; set; }
        public int Rolld { get; set; }
        public string Photo { get; set; }
        public string WorkExperience { get; set; }
        public Nullable<double> Direction { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> DocumentId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Role Role { get; set; }
    }
}
